export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST'
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS'
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL'

export const NEWS_TRENDING_REQUEST = 'NEWS_TRENDING_REQUEST'
export const NEWS_TRENDING_SUCCESS = 'NEWS_TRENDING_SUCCESS'
export const NEWS_TRENDING_FAIL = 'NEWS_TRENDING_FAIL'

export const NEWS_SOURCES_REQUEST = 'NEWS_SOURCES_REQUEST'
export const NEWS_SOURCES_SUCCESS = 'NEWS_SOURCES_SUCCESS'
export const NEWS_SOURCES_FAIL = 'NEWS_SOURCES_FAIL'

export const TRENDING_SOURCE_REQUEST = 'TRENDING_SOURCE_REQUEST'
export const TRENDING_SOURCE_SUCCESS = 'TRENDING_SOURCE_SUCCESS'
export const TRENDING_SOURCE_FAIL = 'TRENDING_SOURCE_FAIL'

export const SOURCES_PARAMS_REQUEST = 'SOURCES_PARAMS_REQUEST'
export const SOURCES_PARAMS_SUCCESS = 'SOURCES_PARAMS_SUCCESS'
export const SOURCES_PARAMS_FAIL = 'SOURCES_PARAMS_FAIL'
